### ISSUE TITLE
PyPi releases

### ISSUE THREAD

**Issue by eu9ene** [hplt-project/OpusCleaner#140]
I see that the last release was on Aug 3 and there were a lot of new features integrated since then. We currently use pip install with git commit but something went wrong and it stopped working for us. See https://github.com/mozilla/firefox-translations-training/issues/292

@jelmervdl would it be possible to release the last changes and maybe configure an automation to release fixes more often?

**Comment by jelmervdl** [comment]
I'll set up the same thing I did on OpusTrainer where releasing a new version is just pushing a tag. That should make it way easier to just push a release every time a feature or bugfix is merged.

**Comment by AmitMY** [comment]
hi @jelmervdl ! really looking forward to this release since it is currently blocking some downstream development

**Comment by jelmervdl** [comment]
Ayy, sorry, I had forgotten about doing the actual release. It's now available as [v0.4.0](https://github.com/hplt-project/OpusCleaner/releases/tag/v0.4.0).

For future reference: tagging a commit with `vX.Y.Z` and then publishing a release will be sufficient to push a new release to Pypi. It will now even automatically fill in the `__about__.py` file since that was one step I always forgot to do manually.
